import os
import smtplib
import wbgapi as wb
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import requests
import io
from datetime import datetime
from email.message import EmailMessage

# --- CONFIGURATION ---
EMAIL_USER = os.environ.get('EMAIL_USER')
EMAIL_PASS = os.environ.get('EMAIL_PASS')

# --- THE CHART DESIGNER ---
def generate_chart(df, title, source, filename):
    try:
        plt.style.use('dark_background')
        fig, ax = plt.subplots(figsize=(10, 14)) # Taller for mobile
        
        # Standardize: Top 12 values
        df = df.iloc[:12]
        
        # Plot: Horizontal Bars (Easier to read)
        # We assume Col 0 is Data, Index is Country
        sns.barplot(x=df.iloc[:, 0], y=df.index, palette='viridis', ax=ax)
        
        # Typography
        ax.set_title(f"{title}\n", fontsize=22, color='white', weight='bold', pad=20)
        plt.text(0, len(df)+1, f"Source: {source} | Generated: {datetime.now().strftime('%Y-%m-%d')}", color='#888888', fontsize=10)
        
        # Clean up
        ax.set_xlabel("")
        ax.set_ylabel("")
        sns.despine(left=True, bottom=True)
        ax.tick_params(axis='y', labelsize=12)
        
        plt.savefig(filename, dpi=100, bbox_inches='tight', facecolor='black')
        plt.close()
        print(f"✅ Created: {filename}")
        return filename
    except Exception as e:
        print(f"⚠️ Skip ({title}): {e}")
        return None

# --- SOURCE 1: WORLD BANK (The Powerhouse) ---
# Covers Economy, Trade, Supply Chain, Social
# --- SOURCE 1: WORLD BANK (Professional Edition) ---
# --- SOURCE 1: WORLD BANK (Professional Edition) ---
def fetch_world_bank():
    print("--- Fetching World Bank Indicators ---")
    indicators = {
        'NY.GDP.MKTP.KD.ZG': 'Top GDP Growth (%)',
        'FP.CPI.TOTL.ZG': 'Highest Inflation Rates (%)',
        'NE.TRD.GNFS.ZS': 'Most Trade-Dependent Economies (% GDP)',
        'LP.LPI.OVRL.XQ': 'Top Logistics Hubs (LPI Score)', 
        'IS.SHP.GOOD.TU': 'Busiest Port Traffic (Million TEU)',
        'SL.UEM.TOTL.ZS': 'Unemployment Rate (%)',
        'EN.ATM.CO2E.PC': 'CO2 Emissions Per Capita',
        'IT.NET.USER.ZS': 'Internet Penetration (%)'
    }
    
    charts = []
    for code, title in indicators.items():
        try:
            # Fetch data
            df = wb.data.DataFrame(code, mrv=1, labels=True)
            
            # Sort Logic
            ascending = True if "Unemployment" in title else False
            df = df.sort_values(by=df.columns[1], ascending=ascending)
            
            # Unit Conversions
            if 'TEU' in title:
                df.iloc[:, 0] = df.iloc[:, 0] / 1000000
            
            # Clean Index (Change 'SGP' to 'Singapore' if possible, or just keep codes)
            # This version keeps it simple to avoid crashes
            
            filename = f"wb_{code}.png"
            # Note: We removed the emoji from the title below
            if generate_chart(df, title, "World Bank Open Data", filename):
                charts.append(filename)
        except Exception as e:
            print(f"Failed {code}: {e}")
    return charts
# --- SOURCE 3: SIPRI (Military Excel) ---
def fetch_sipri_military():
    print("--- Fetching Military Data ---")
    charts = []
    try:
        url = "https://www.sipri.org/sites/default/files/SIPRI-Milex-data-1949-2024.xlsx"
        r = requests.get(url, headers={'User-Agent': 'Mozilla/5.0'})
        with io.BytesIO(r.content) as f:
            df = pd.read_excel(f, sheet_name="Current USD", skiprows=5)
            
        latest_year = df.columns[-1]
        df = df[['Country', latest_year]].dropna().sort_values(by=latest_year, ascending=False).set_index('Country')
        
        filename = "sipri_defense.png"
        if generate_chart(df, f"🛡️ Top Military Budgets ({latest_year})", "SIPRI", filename):
            charts.append(filename)
    except Exception as e:
        print(f"SIPRI Error: {e}")
    return charts

# --- EMAILER ---
def send_email(attachments):
    if not attachments:
        print("❌ No charts generated.")
        return

    print(f"📧 Sending {len(attachments)} charts...")
    msg = EmailMessage()
    msg['Subject'] = f"📊 Daily Intelligence: {len(attachments)} Charts Ready"
    msg['From'] = EMAIL_USER
    msg['To'] = EMAIL_USER
    msg.set_content("Here is your daily automated market intelligence briefing.\n\nGenerated by Python via GitHub Actions.")

    for file in attachments:
        with open(file, 'rb') as f:
            msg.add_attachment(f.read(), maintype='image', subtype='png', filename=file)

    with smtplib.SMTP_SSL('smtp.gmail.com', 465) as smtp:
        smtp.login(EMAIL_USER, EMAIL_PASS)
        smtp.send_message(msg)
    print("🎉 Email Sent!")

# --- MAIN RUN ---
if __name__ == "__main__":
    all_files = []
    all_files.extend(fetch_world_bank())     # Covers 8 topics
    all_files.extend(fetch_wiki_energy())    # Covers Energy
    all_files.extend(fetch_sipri_military()) # Covers Defense
    
    send_email(all_files)
