import os
import smtplib
import wbgapi as wb
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import random
from datetime import datetime
from email.message import EmailMessage

# --- CONFIGURATION ---
EMAIL_USER = os.environ.get('EMAIL_USER')
EMAIL_PASS = os.environ.get('EMAIL_PASS')

# --- DATA GENERATOR (Same as before) ---
def get_supply_chain_chart():
    print("Fetching Supply Chain Data...")
    metrics = {
        'LP.LPI.OVRL.XQ': {'title': "📦 Top Logistics Hubs (LPI Score)", 'xlabel': "Efficiency Score (1-5)"},
        'IS.SHP.GOOD.TU': {'title': "🚢 Busiest Ports (Million TEU)", 'xlabel': "TEU"},
        'NE.CON.PRVT.PC.KD': {'title': "🛍️ Top Consumer Markets", 'xlabel': "Spending Per Capita (USD)"}
    }
    code = random.choice(list(metrics.keys()))
    info = metrics[code]
    
    df = wb.data.DataFrame(code, mrv=1, labels=True)
    df = df.sort_values(by=df.columns[1], ascending=False).head(10)
    if code == 'IS.SHP.GOOD.TU': df.iloc[:, 0] = df.iloc[:, 0] / 1000000 
    
    # Create Chart
    plt.style.use('dark_background')
    fig, ax = plt.subplots(figsize=(9, 16))
    sns.barplot(x=df.iloc[:, 0], y=df.index, palette='viridis', ax=ax)
    ax.set_title(f"{info['title']}\n", fontsize=24, color='white', weight='bold')
    sns.despine(left=True, bottom=True)
    
    filename = "daily_post.png"
    plt.savefig(filename, dpi=150, bbox_inches='tight', facecolor='black')
    return filename, info['title']

# --- EMAIL SENDER (The New Part) ---
def send_email(filename, subject):
    print("Preparing Email...")
    
    msg = EmailMessage()
    msg['Subject'] = f"📊 Daily Update: {subject}"
    msg['From'] = EMAIL_USER
    msg['To'] = EMAIL_USER # Sending to yourself
    msg.set_content("Here is your automated Supply Chain Market Intelligence report.\n\nGenerated by Python on GitHub Actions.")

    # Attach the Image
    with open(filename, 'rb') as f:
        file_data = f.read()
        file_name = f.name
    msg.add_attachment(file_data, maintype='image', subtype='png', filename=file_name)

    # Send via Gmail
    try:
        with smtplib.SMTP_SSL('smtp.gmail.com', 465) as smtp:
            smtp.login(EMAIL_USER, EMAIL_PASS)
            smtp.send_message(msg)
        print("🎉 SUCCESS: Email sent successfully!")
    except Exception as e:
        print(f"❌ FAIL: Could not send email. Error: {e}")
        raise e

# --- MAIN CONTROLLER ---
if __name__ == "__main__":
    try:
        image_file, title = get_supply_chain_chart()
        send_email(image_file, title)
    except Exception as e:
        print(f"Workflow Failed: {e}")
        # This exit code ensures GitHub shows a Red X if it fails
        exit(1)
